#!/usr/local/bin/zsh
. $HOME/.zshenv # load the env variable

# save buffers, restarts the server & all client frames associated with it
# only kill emacs if server is already running, otherwise, just reload launchctl
echo "Killing existing emacs server..."
emacsclient -e "(save-buffers-kill-emacs)" 2> /dev/null

# reloads using launchctl
echo "Relaunching emacs server using launchd..."
launchctl unload ~/Library/LaunchAgents/gnu.emacs.daemon.LaunchAtLogin.agent.plist
launchctl load ~/Library/LaunchAgents/gnu.emacs.daemon.LaunchAtLogin.agent.plist
